/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export default function FrontCloud({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('./src/assets/cloud.glb')

  useFrame((state, delta) => {
    if(group.current.position.x < -40) {
      group.current.position.x = 25
    } else {
      group.current.position.x -= 0.01
    }
  })

  return (
    <group ref={group} {...props} dispose={null} position={[30, -10, -5]} rotation={[0, 1.3, 0]} scale={2.7}>
      <mesh geometry={nodes.cloud.geometry} material={materials.Material} position={[-0.17, 0.63, 2.84]} scale={1.34} />
    </group>
  )
}

useGLTF.preload('./src/assets/cloud.glb')
